### ISSUE TITLE
Split gobject-introspection into multiple outputs

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/gobject-introspection-feedstock#32]
The idea springs from [this comment](https://github.com/conda-forge/gdk-pixbuf-feedstock/pull/24#issuecomment-709498213), which references [this nice overview](https://gi.readthedocs.io/en/latest/). It's also motivated by the recent shift by `gtk3` and `gdk-pixbuf` to move `gobject-introspection` from a host dependency to a build dependency since they use `g-ir-scanner` as a build tool. It would be nice to do similar with other packages, but `pygobject` for example actually needs parts of the current `gobject-introspection` (`libgirepository`) as a run dependency. I'm making this issue to foster discussion and act as a reminder.

You can see how Debian splits `gobject-introspection` [here](https://packages.debian.org/source/sid/gobject-introspection). At a minimum, I'd say it would be nice to have a separate `libgirepository` package. I'm less clear about the utility of the further splits that Debian has (aside from the typical base and "-dev" splits which is not typically something that conda-forge does).

**Comment by pkgw** [comment]
I'm removing the question mark here. This is definitely something that we should do ... someone just needs to sit down and do it.

**Comment by tschoonj** [comment]
Sounds good, even though for now it would only really be useful for pygobject. Other packages that could benefit from this are libpeas and edit, which are linked against libgirepository, but currently not available in conda-forge.

Note that this won't change anything regarding the mess that is the meson/gobject-introspection combo that needs to go into build.

**Comment by ryanvolz** [comment]
Report [here](https://github.com/gnuradio/gnuradio/issues/4420#issuecomment-904302658) of missing typelib for `harfbuzz` on osx-arm64, which is currently built with introspection disabled because of cross-compilation. I'm guessing the issue with cross-compilation would be solved by a split `gobject-introspection`, so I'm noting it here so it can be followed up later once this is implemented.
