### ISSUE TITLE
g-ir-scanner points to system python

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/gobject-introspection-feedstock#64]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

g-ir-scanner starts with a 

```
#!/usb/bin/python3
```

But it should really point to the prefix.

### Installed packages

```shell
.
```

### Environment info

```shell
1.74.0
```

**Comment by hmaarrfk** [comment]
I tried to dig into this, but I couldn't ifnd how the file is generated from the source. sorry :/

**Comment by hmaarrfk** [comment]
Hmm, i guess it seems to be pointing to 

```
/usr/bin/env python
```

which may be ok, except for cross compiling.

I think the following patch does the trick, but I'm not sure which is better:

```patch
diff -ur a/tools/meson.build b/tools/meson.build
--- a/tools/meson.build 2022-09-17 14:52:38.000000000 -0400
+++ b/tools/meson.build 2023-04-01 23:46:27.513915405 -0400
@@ -12,7 +12,7 @@
 if cc.get_id() == 'msvc'
   python_cmd = '/usr/bin/env ' + python.path()
 else
-  python_cmd = '/usr/bin/env python@0@'.format(python.language_version().split('.')[0])
+  python_cmd = join_paths(get_option('prefix'), 'bin', 'python')
 endif

 tool_output = []

```

**Comment by pkgw** [comment]
I feel like it is probably going to be better to stick with the `env` approach here. In cross-compiling situations there's a lot going on but I believe that it's reasonable to ask that $PATH only contain programs that we can run, and that the first `python` in $PATH should be the one that we ought to be running in any given circumstance. Do you have a specific example of a build case where `env` is running the wrong Python while a hardcoded prefix would be correct?

**Comment by hmaarrfk** [comment]
yeah, sorry, all this was mostly noise for me trying to learn that g-ir-scanner just needs to be able to run on a native or emulated machine.
